import type { Metadata } from "next";
import "./styles/fonts.css";
import "./styles/globals.css";
import "material-icons/iconfont/material-icons.css";
import "material-symbols";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="max-w-[1440px] mx-auto px-16 py-8">{children}</main>
      </body>
    </html>
  );
}
